#!/bin/bash

echo "WARNING: Influx operates on port 3000 by default. If you need to change this, please reference /etc/influx/config.yml when the install process is complete.";
echo "Influx: Running installer in 3s";
sleep 3;

apt -y install curl;

mkdir -p /etc/influx;
curl -L -o /etc/influx/config.yml "https://raw.githubusercontent.com/cmrxnn/influx-agent/develop/config.yml.example"

curl -L -o /usr/local/bin/influx "https://github.com/cmrxnn/influx-agent/releases/latest/download/influx_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")";

chmod u+x /usr/local/bin/influx;

echo "[Unit]
Description=InfluxAgent
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/influx

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/influx.service;

systemctl enable --now influx;

echo "Influx: Install completed, checking systemd process...";

systemctl status influx;